name: 📖 Documentation
description: For issues with the Typst Agent documentation
title: Write a short and descriptive title!
labels:
  - docs
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an issue with Typst Agent documentation. Please search the downstream issue tracker first. Documentation issues submitted here remain downstream.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue.
      placeholder: Terse and specific description of the issue. You can add a screenshot by dragging an image here.
    validations:
      required: true
